---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-admin-pass
  namespace: default
spec:
  encryptedData:
    password: AgBjF4dlRCw0lc20zStYM3RJNquZeJt+no8AL4/ii/WuyUMf58eYjglKPzbfPfsPzCDbd/SlTNCSy6t0dSvrMfbABpF1b3M7AcYZFpJ81a42jBI+ocvIa6VgW5lJ1Q6QeQmzHiUxzuYGRvQGLeci+2LGi4czIfRHV9s6UbBVLJ+zmAU6g98iZzD/Yr5D+rXaBH8Ty8a5LSX8yXPTdec9iNXbRrtzWn3sBb6EWJJhuWhKzcxozm96f5n8xJV1QGgajTNpcWyR/2nfJrRtJFafGPdtnT6r+y3Vc+GZhWvr3N641wQmmMavBWYcY7pmsaRvciTPkbKoL/xLYV5XA/3qnAQSmWkoVCJNtXJrRUoiot48r2IBdi9eQ3qYChVUUgprgojcvHzwkxaI/lvbYTck+PkR2aPalsh9znYX7IMf5O8QRUV5OHDwJVTyXLM77ZiYn7PAh5W7/5Sb/3QAAH5Khv0NorGjZ1Fy48ZsjSIHISYZjq3Iv1tDYeFjc2wvLDMcMNJ2ieAhYxEgxNXKNv4Z5BWBnNcszhiwLAqbzSA7MoR9B4Ll/KvoOLYV0ihJKMkCSvD9/CCuGJ1KRSwx45Tw/3YcQjr40TXbo8SzzIZvt00LRGZW7uWcu2Y8DOoy2/+pE023Mq77NqJ5nRhoXa3T+SBlBDfDFWfwxP62GGXliRiQUKNLmJYaNpyKb+kgWlE6TZbfCjj6/LjTqA==
  template:
    metadata:
      name: jenkins-admin-pass
      namespace: default
